name: iOS Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:
        
    
permissions:
  id-token: write
  contents: write

jobs:
  increment_version:
    name: Increment Version
    runs-on: macos-26
    steps:
      - name: Add Path Globally
        run: echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # pin@v4
        with:
          fetch-depth: 0
          
          
          
      - name: Increment Version
        id: versioning
        uses: benmckillop/Versioning@making-use-of-prerelease-flag
        with:
          ACTION_TYPE: 'Release'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
