name: Manual iOS Deploy

on:
  workflow_dispatch:
    inputs:
      build_configuration:
        description: 'Which build configuration to use'
        required: true
        default: 'Staging'
        type: choice
        options:
        - Dev
        
    
permissions:
  id-token: write
  contents: write

jobs:
  increment_version:
    name: Increment Version
    runs-on: macos-26
    steps:
      - name: Add Path Globally
        run: echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # pin@v4
        with:
          fetch-depth: 0
          
      - name: Increment Version
        id: versioning
        uses: benmckillop/Versioning@feature/adding-optional-suffix-to-release-version
        with:
          ACTION_TYPE: 'Release'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SUFFIX: 'alphaa'
